### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by LukasSliacky** [chfw/Flask-Excel#1]
Hi jaska,
thanks for your Flask Extension: Flask-Excel.

When i try your example app: "tiny_example.py" and upload file: /examples/example_for_upload.csv, response from flask in browser is: "Bad Request, The browser (or proxy) sent a request that this server could not understand."

Can you help me with solution?
(when you need more information, pls contact me)

Thanks.
Lukas
(Python 3.4)

**Comment by chfw** [comment]
Thanks for reporting.
