### ISSUE TITLE
Flasky integration

### ISSUE THREAD

**Issue by LukasSliacky** [chfw/Flask-Excel#2]
Hi jaska,
(i am flask beginner) and i have one question: 

after your fix (bad request) works your scripts fine...

But when i can integrate it to my flask application based on Miguel Grinberg`s Flasky (https://github.com/miguelgrinberg/flasky/commits/master?page=2), after upload CSV file, app show error :"AttributeError: 'Request' object has no attribute 'get_array'"

(Maybe it`s trivial probem, but with my skill of Flask, i don`t know, how i doing wrong...)

Can you help me?

Thank you.
Lukas

**Comment by chfw** [comment]
Have you done this in your file?

    from flask.ext import excel

**Comment by LukasSliacky** [comment]
Oh, mea cupla... 
Now all works fine.
