### ISSUE TITLE
Not working with Flask-Restful

### ISSUE THREAD

**Issue by ueg1990** [chfw/Flask-Excel#4]
Hello, 

I came across your extension yesterday and I was unable to integrate your example code with flask excel. This is how i was trying to use it:

class Users(restful.Resource):
    def post(self):
        return jsonify({"result": request.get_array(field_name='file')})

But all is got was an array: {"result" : []}

It is not the worse thing in the world but it would be nice to have a way to integrate flask-restful with flaks-excel. Let me know what you think and if there is anyway i can help.

Usman

**Comment by chfw** [comment]
'field_name' refers to the name of file upload field of the html form. I am not sure how you have uploaded your file. Here is a working example based on the quick start guide of Flask-Restful: 

```
from flask import Flask, request, jsonify
from flask.ext import excel
from flask_restful import Resource, Api


app = Flask(__name__)
api = Api(app)

class HelloWorld(Resource):
    def get(self):
        return {'hello': 'world'}
    # modification starts  ---->
    def post(self):
        return jsonify({"results": request.get_array(field_name='file')})

@app.route("/upload", methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        return jsonify({"result": request.get_array(field_name='file')})
    return '''
    <!doctype html>
    <title>Upload an excel file</title>
    <h1>Excel file upload (csv, tsv, csvz, tsvz only)</h1>
    <form action="/" method=post enctype=multipart/form-data><p>
    <input type=file name=file><input type=submit value=Upload>
    </form>
    '''
    # <---- modification ends
    
api.add_resource(HelloWorld, '/')

if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by chfw** [comment]
I am closing this issue as I assume my previous code example provide some hints on your problem. Please re-open it otherwise.
