### ISSUE TITLE
make_response_from_records returns deprecated warning

### ISSUE THREAD

**Issue by rotten** [chfw/Flask-Excel#6]
When make_response_from_records() is invoked it displays a warning:

"Deprecated since v0.1.5! Please use get_sheet instead."

I'm using Flask-Excel (0.0.3) with pyexcel (0.1.7).

It looks like it is coming out of code here:  https://github.com/chfw/pyexcel/blob/master/pyexcel/deprecated.py

**Comment by chfw** [comment]
Yes, this issue is valid. I will find time to fix it in pyexcel-webio v 0.4.

**Comment by chfw** [comment]
Please try this:

    pip install pyexcel-webio==0.0.4

and the deprecation warning shall go away. Please let me know how it goes.

**Comment by rotten** [comment]
A quick test in my development environment reveals that this version bump does indeed get rid of the warning.  Thanks!!

**Comment by chfw** [comment]
Cheers!

For others' information,  new installation of Flask-Excel v0.0.3 will pick up pyexcel-webio v0.0.4 automatically. For existing installation of FE v0.0.3, you shall install pw v0.0.4.
